name: Prevent Develop Deletion
on:
  delete:
    branches:
      - develop

jobs:
  restore_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Restore Develop Branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git clone https://github.com/${{ github.repository }}.git
          cd $(basename ${{ github.repository }})
          git checkout -b develop origin/main
          git push origin develop
